### PR TITLE
Fixed to support python 3

### PR DESCRIPTION
**Pull request by ssshah86**
urllib2 doesn't exist within python3. The proposed changes should be compatible with python2 and 3, tested on 2.7.13 and 3.6.0.

Sorry looks like I commited this early without running more tests, let me refine & push a new update to fix compatibility with both Python2 and 3.

### CODE REVIEW

**Comment by schickling** [comment]
Thanks a lot for this great contribution!

**Comment by rcy** [comment]
Does the version need to be bumped in `setup.py` and a new version uploaded to pypi?

**Comment by ssshah86** [comment]
Yes, I believe the graphcool team is pretty busy and will get to that soon.

**Comment by schickling** [comment]
It's been a while since we've dealt with Python packages the last time. What's the command needed to publish a new version @ssshah86?

**Comment by ssshah86** [comment]
`<python setup.py register -r pypi>`
and
`<python setup.py sdist upload -r pypi>`

But @rcy is right, the version should be incremented first otherwise PyPI will reject it.

see: http://sherifsoliman.com/2016/09/30/Python-package-with-GitHub-PyPI/#release-testing

**Comment by schickling** [comment]
This is what I'm getting here. Can I add you as a collaborator somehow?

image

**Comment by ssshah86** [comment]
Yea my PyPI u/n is ssshah86, but I believe you have to update it in setup.py for me to be a maintainer though.

I think it's the version of Python you are using, 3.5.2. There's an update in distutils for 3.5.3 that uploads to `pypi.org` instead of `pypi.python.org`, which was shut down July 3rd. 

What's the repository information in your `.pypirc` file? If you upgrade you can delete the line starting with `repository` and you will use your upload tool’s default URL.

OR you can also use twine by installing it via `pip3 install twine`, which should be version 1.9.x. Then after  you build your source dist, you can use `twine upload --repository testpypi dist/*` where the `--repository` flag will read from your` .pypirc` file.

**Comment by schickling** [comment]
Added you as an owner on PyPI!

**Comment by ssshah86** [comment]
Thanks. Just uploaded v0.2.0. Everything looks great. There's one issue when upgrading on OSX when installing something with a dependency on the package 'six', detailed here: https://github.com/pypa/pip/issues/3165

**Comment by ssshah86** [comment]
you can uninstall and reinstall to avoid the error

**Comment by rcy** [comment]
Just installed 0.2.0 here, everything is working great... thank you both for your work!

**Pull request merged**
